FROM ubuntu:18.04

RUN apt-get update              \
    && apt-get install -y       \
    nginx                       \
    php-fpm                     \
    php7.2-mysql                \
    php7.2-intl                 \
    php7.2-mbstring             \
    php7.2-zip                  \
    php7.2-xml                  \
    php7.2-curl                 \
    php-gearman

#
# When added to the first run command it opens up a tzconfig question
# and will not finish installation. have this on separate RUN instead
#
RUN apt-get install -y git

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/php.ini /etc/php/7.2/fpm/php.ini
COPY docker/default /etc/nginx/sites-available/default

WORKDIR /var/www/html

CMD service php7.2-fpm start    \
    && nginx -g 'daemon off;'   \
    && bash